sudo: false

language: 'c'

addons:
  apt:
    sources:
      - 'ubuntu-toolchain-r-test'
    packages:
      - 'gcc-7'

before_install:
  - 'export CC=gcc-7'

before_script:
  - 'make build'

script:
  - 'make test'
  - 'make functional'
